version: 2.1

jobs:
  build-test:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run:
          name: 'Install packages'
          command: yarn install
      - run:
          name: 'Build'
          command: yarn build
      - run:
          name: 'Run tests'
          command: yarn test

workflows:
  ci:
    jobs:
      - build-test
