version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run:
          name: 'Install packages'
          command: yarn install
      - run:
          name: 'Run tests'
          command: yarn test

workflows:
  test-build:
    jobs:
      - test
