version: 2.1

jobs:
  build-test:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: 'Echo turbo dry json'
          command: yarn diff
      - run:
          name: Build
          command: yarn build
      - run:
          name: Run tests
          command: yarn test

  playground:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Run script
          command: ./.circleci/scripts/turbo-changed.sh

workflows:
  ci:
    jobs:
      - playground
